id: d4050a79a5a34ba1a028187a288726b8
initial_creation_type: ocr
source_metadata:
  volumes:
    eea8dec06cd84b5198d11a6ba42b02e8:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: ''
      total_pages: 2107
      volume_number: 11
